[app]
name = "HAB Flash"
category = "Badge"
wifi_preference = true

[entry]
class = "HabFlash"

[metadata]
author = "Tom Dalby"
license = "MIT"
url = "https://github.com/ThomasJackDalby/tildagon-flashy"
description = "The essential navigation (and tracking) tool for EMF 2024. Allows the wearer to beam their current location to HABVille, through the medium of receipt printing. (to be clear, this will actually print a physical receipt of your location at HABVille (during EMF 2024))."
version = "0.0.4"